# Generated by Django 4.0 on 2021-12-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Costperitem', models.IntegerField(default=0)),
                ('Stockquantity', models.IntegerField(default=0)),
                ('Volume', models.IntegerField(default=0)),
            ],
        ),
    ]
