# Generated by Django 4.0 on 2021-12-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('Name', 'Description', 'Costperitem', 'Stockquantity')},
        ),
    ]
