# Generated by Django 4.0 on 2021-12-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_product_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Costperitem',
            new_name='item_cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Stockquantity',
            new_name='stock_quantity',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Volume',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
